wandb_version: 1

datamodule:
  value:
    batch_size: 128
    data_dir: /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/PREPROCESSED_DATA/S01/eeg/P10_01.npy
    num_workers: 0
    seed: 42
    val_run: /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/S02/val/data.npy
final_model:
  value: false
fine_tuning:
  value: false
model:
  value:
    D: 2
    F1: 64
    drop_prob: 0.5
    final_conv_length: auto
    in_chans: 64
    input_window_samples: 4096
    kernel_length: 64
    lr: 0.002883341255613476
    momentum: 0.1
    n_classes: 6
    one_cycle_lr: true
    pool_mode: max
    weight_decay: 0.007946893040378412
model_name:
  value: EEGNET
trainer:
  value:
    max_epochs: 30
