name: EEGNet_Embedding
program: train.py
method: random
run_cap: 1
metric:
  goal: maximize
  name: val_acc
parameters:
  model_name: 
    value: EEGNET_Embedding
  final_model:
    value: True
  trainer:
    parameters:
      max_epochs:
        value: 30 
  fine_tuning:
    value: False
  datamodule:
    parameters:
      data_dir: 
        value: "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train"
      test_dir:
        value: "/Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/test/"
      test_run:
        value: "data.npy" #test set
      batch_size:
        value: 128
      num_workers:
        value: 0
      seed:
        value: 42
  model:
    #General
    parameters:
      in_chans: 
        value: 64
      n_classes:
        value: 6
      lr:
        value: 0.006792587242214172
      one_cycle_lr:
        value: True
      weight_decay:
        value: 0.007401750417946161
      input_window_samples:
        value: 4096
      final_conv_length:
        value: "auto"
      
      #Convolutional Module
      F1:
        value: 64 
      D:
        value: 2
      kernel_length:
        value: 64 
      pool_mode:
        value: "max"
      drop_prob:
        value: 0.25
      momentum:
        value: 0.1 