wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727474912
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 103
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.17.8
      6: 4.44.2
      8:
      - 5
      13: darwin-x86_64
datamodule:
  desc: null
  value:
    batch_size: 64
    data_dir: /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/train/P10train.npy
    num_workers: 0
    seed: 42
    val_run: /Users/arnavkapur/Desktop/Analysis_3DImagery/imagery2024/Generation/Segmented_data/val/P10val.npy
final_model:
  desc: null
  value: false
fine_tuning:
  desc: null
  value: false
model:
  desc: null
  value:
    D: 2
    F1: 16
    drop_prob: 0.25
    final_conv_length: auto
    in_chans: 64
    input_window_samples: 4096
    kernel_length: 64
    lr: 0.014190370099091867
    momentum: 0.1
    n_classes: 6
    one_cycle_lr: true
    pool_mode: max
    weight_decay: 0.0015742413730855883
model_name:
  desc: null
  value: EEGNET
trainer:
  desc: null
  value:
    max_epochs: 30
lr:
  desc: null
  value: 0.014190370099091867
one_cycle_lr:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0.0015742413730855883
epochs:
  desc: null
  value: 30
in_chans:
  desc: null
  value: 64
n_classes:
  desc: null
  value: 6
final_conv_length:
  desc: null
  value: auto
input_window_samples:
  desc: null
  value: 4096
F1:
  desc: null
  value: 16
D:
  desc: null
  value: 2
kernel_length:
  desc: null
  value: 64
pool_mode:
  desc: null
  value: max
drop_prob:
  desc: null
  value: 0.25
momentum:
  desc: null
  value: 0.1
